const KEY='miFinanzasDarwinV1';
const defaults={income:4750000,baseExpenses:1445000,carPayment:535000,carBalance:23500000,carRate:.1906,bancolombia:121000,bancolombiaLimit:35700000,rappi:2800000,rappiLimit:7800000,rappiInstallments:2,cash:2000000,pending:450000,emergency:5000000,baby:10000000,home:160000000,subsidy:35018100,homeClosing:12981900,carValue:24000000,travelNov:1000000,travelAfter:400000,cesantias:3000000};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{settings:defaults,transactions:[]};
const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Math.round(n||0));
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const sumOut=()=>state.transactions.filter(x=>['Gasto','Pago deuda'].includes(x.type)).reduce((a,x)=>a+x.amount,0);
const sumIn=()=>state.transactions.filter(x=>['Ingreso','Prima'].includes(x.type)).reduce((a,x)=>a+x.amount,0);
function render(){const s=state.settings; const txOut=sumOut(),txIn=sumIn();
 document.getElementById('income').textContent=money(s.income); document.getElementById('baseExpenses').textContent=money(s.baseExpenses); document.getElementById('debtTotal').textContent=money(s.carBalance+s.rappi+s.bancolombia);
 document.getElementById('cardUse').textContent=((s.bancolombia/s.bancolombiaLimit+s.rappi/s.rappiLimit)/2*100).toFixed(1)+'%';
 document.getElementById('available').textContent=money(s.cash-s.pending+txIn-txOut);
 const status=(s.rappi+s.bancolombia<=121000)?'EN ORDEN':'BAJAR TARJETAS'; document.getElementById('status').textContent=status;
 const goals=[['Fondo emergencia',s.emergency,Math.min(s.emergency,s.cash-s.pending),money(Math.min(s.emergency,s.cash-s.pending))],['Fondo bebé',s.baby,state.transactions.filter(x=>x.category==='Bebé'&&x.type==='Ahorro').reduce((a,x)=>a+x.amount,0),'' ],['Vivienda',s.homeClosing,state.transactions.filter(x=>x.category==='Vivienda futura'&&x.type==='Ahorro').reduce((a,x)=>a+x.amount,0),'' ]];
 document.getElementById('goals').innerHTML=goals.map(g=>{let p=Math.min(100,g[2]/g[1]*100);return `<div class="goalrow"><div class="row"><b>${g[0]}</b><span>${money(g[2])} / ${money(g[1])}</span></div><div class="progress"><div class="bar" style="width:${p}%"></div></div></div>`}).join('');
 document.getElementById('actions').innerHTML=['Pagar Bancolombia completo.','Completar las 2 cuotas de RappiCard y no financiar nuevo consumo.','Octubre: cero viajes.','Noviembre: viaje máximo $1.000.000.','Construir fondo de emergencia antes de aumentar gastos.','Preparar preaprobación hipotecaria para VIS de $160 M.'].map(x=>`<li>${x}</li>`).join('');
 document.getElementById('debtCards').innerHTML=[['Crédito carro',s.carBalance,s.carPayment,'19,06% E.A.','Evaluar venta vs. conservación.'],['RappiCard',s.rappi,s.rappi/2,'Tasa por verificar','2 cuotas restantes.'],['Bancolombia',s.bancolombia,s.bancolombia,'Tasa por verificar','Pagar completo.']].map(d=>`<div class="card debt ${d[1]>1000000?'danger':''}"><div class="row"><h3>${d[0]}</h3><b>${money(d[1])}</b></div><p class="muted">Pago/mes: ${money(d[2])} · ${d[3]}</p><p>${d[4]}</p></div>`).join('');
 document.getElementById('goalDetails').innerHTML=`<div class="card"><h3>Emergencia</h3><p>${money(Math.min(s.emergency,s.cash-s.pending))} de ${money(s.emergency)}</p></div><div class="card"><h3>Bebé</h3><p>${money(goals[1][2])} de ${money(s.baby)}</p></div><div class="card"><h3>Vivienda VIS</h3><p>Objetivo: ${money(s.home)}</p><p>Subsidio referencia: ${money(s.subsidy)}</p><p>Cierre/ahorro de referencia: ${money(s.homeClosing)}</p></div>`;
 const list=[...state.transactions].reverse(); document.getElementById('txList').innerHTML=list.length?list.map((x,i)=>`<div class="tx"><div><b>${x.category}</b><div class="muted">${x.date} · ${x.desc||x.type} · ${x.method}</div></div><strong class="amount ${['Ingreso','Prima','Ahorro'].includes(x.type)?'in':'out'}">${['Ingreso','Prima','Ahorro'].includes(x.type)?'+':'-'}${money(x.amount)}</strong></div>`).join(''):'<p class="muted">Aún no hay movimientos.</p>';
 renderSettings();
}
function renderSettings(){const s=state.settings; const fields=[['income','Ingreso mensual'],['baseExpenses','Gastos recurrentes'],['carPayment','Cuota carro'],['carBalance','Saldo carro'],['bancolombia','Saldo Bancolombia'],['rappi','Saldo RappiCard'],['cash','Caja actual'],['pending','Pagos pendientes'],['emergency','Meta emergencia'],['baby','Meta bebé'],['home','Valor vivienda'],['subsidy','Subsidio referencia'],['homeClosing','Ahorro/cierre vivienda'],['travelNov','Viaje noviembre'],['travelAfter','Viajes posteriores'],['carValue','Valor venta carro']]; document.getElementById('settingsForm').innerHTML=fields.map(f=>`<div class="setting-row"><label>${f[1]}</label><input type="number" data-key="${f[0]}" value="${s[f[0]]}"></div>`).join('');}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(b.dataset.view).classList.add('active');});
document.getElementById('txForm').onsubmit=e=>{e.preventDefault();const amount=+document.getElementById('amount').value;if(!amount)return;state.transactions.push({date:new Date().toLocaleDateString('es-CO'),type:document.getElementById('type').value,category:document.getElementById('category').value,method:document.getElementById('method').value,desc:document.getElementById('desc').value,amount});save();e.target.reset();document.getElementById('saved').classList.remove('hidden');setTimeout(()=>document.getElementById('saved').classList.add('hidden'),1800);render();};
document.getElementById('saveSettings').onclick=()=>{document.querySelectorAll('#settingsForm input').forEach(i=>state.settings[i.dataset.key]=+i.value);save();render();alert('Configuración guardada.');};
document.getElementById('clearTx').onclick=()=>{if(confirm('¿Borrar todos los movimientos?')){state.transactions=[];save();render();}};
document.getElementById('resetBtn').onclick=()=>{if(confirm('¿Restablecer toda la información?')){localStorage.removeItem(KEY);location.reload();}};
render();
